name: Publish package to NPM registry
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Test
        run: |
          npm i
          npm run lint:format
          npm run test
          npm run build
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Node.js 16.x and setup npmrc
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
<<<<<<< HEAD
      - env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTO_TOKEN}}
      - run: echo ${{secrets.NPM_AUTO_TOKEN}}
=======
      - run: npm adduser --registry=https://registry.npmjs.org --scope=@riquely --always-auth
>>>>>>> c531efe2b9bf9a5d9a5d2d0026145b7b05af92c4
      - run: npm i
      - run: npm publish --access public

